version = 0.1.0
java_name = cascara.format.vsix
maven_name = cascara-format-vsix
group = io.github.qishr
title = Cascara VSIX Package Support
description = Cascara VSIX file format and utilities
url = https://qishr.github.io/javadoc/cascara.format.vsix/
scm_url = https://github.com/qishr/cascara-format-vsix
scm_conn = scm:git:https://github.com/qishr/cascara-format-vsix.git
scm_dev_conn = scm:git:https://github.com/qishr/cascara-format-vsix.git

org.gradle.configuration-cache = false


