plugins {
    id 'java'
    id 'java-gradle-plugin'
    id 'com.gradle.plugin-publish' version '2.1.0'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

repositories {
	mavenLocal()
    mavenCentral()
}

dependencies {
    implementation(platform("io.github.qishr:cascara-meta-bom:$cascara_version"))
    implementation "io.github.qishr:cascara-common"
    implementation "io.github.qishr:cascara-common-io"

    implementation(project(":vsix-format"))
}

gradlePlugin {
    website = "https://qishr.github.io/cascara/file-formats/vsix/gradle-plugin/"
    vcsUrl = "https://github.com/qishr/cascara-format-vsix.git"
    plugins {
        vsixPlugin {
            id = "io.github.qishr.cascara-gradle-plugins.vsix"
            implementationClass = "io.github.qishr.cascara.gradle.vsix.VsixPlugin"
            displayName = 'Cascara VSIX Packaging Plugin'
            description = 'Declarative Gradle plugin for packaging VS Code VSIX extension bundles without requiring Node.js or vsce.'
            tags = ['cascara', 'vsix', 'file-format', 'vscode', 'packaging', 'extension']
            compatibility {
                features {
                    configurationCache = true
                }
            }
        }
    }
}

